Rapport 2

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -30,30 +30,30 @@ jobs:
           echo "REDIS_PORT=6379" >> .env
           echo "REDIS_DB=0" >> .env
 
-      - name: Démarrer le conteneur
-        run: |
-          docker network create labo04-network
-          docker compose up -d
+      # - name: Démarrer le conteneur
+      #   run: |
+      #     docker network create labo04-network
+      #     docker compose up -d
 
-      - name: Attendre MySQL
-        run: |
-          sleep 10
-          timeout=60
-          until docker compose exec -T mysql mysqladmin ping -h localhost -u root -proot --silent; do
-            echo "Waiting for MySQL..."
-            sleep 3
-            timeout=$((timeout - 3))
-            if [ $timeout -le 0 ]; then
-              echo "MySQL failed to start"
-              exit 1
-            fi
-          done
-          sleep 5
+      # - name: Attendre MySQL
+      #   run: |
+      #     sleep 10
+      #     timeout=60
+      #     until docker compose exec -T mysql mysqladmin ping -h localhost -u root -proot --silent; do
+      #       echo "Waiting for MySQL..."
+      #       sleep 3
+      #       timeout=$((timeout - 3))
+      #       if [ $timeout -le 0 ]; then
+      #         echo "MySQL failed to start"
+      #         exit 1
+      #       fi
+      #     done
+      #     sleep 5
 
-      - name: Éxécuter les tests et capturer les logs
-        run: |
-          docker compose exec -T store_manager pytest /app/src/tests/test_store_manager.py
+      # - name: Éxécuter les tests et capturer les logs
+      #   run: |
+      #     docker compose exec -T store_manager pytest /app/src/tests/test_store_manager.py
 
-      - name: Cleanup
-        if: always()
-        run: docker compose down -v
+      # - name: Cleanup
+      #   if: always()
+      #   run: docker compose down -v
